- hosts: all
  tasks:
  - name: install the latest version of Apache
    yum:
      name: httpd
      state: latest
  - name: Start service httpd, if not started
    service:
      name: httpd
      state: started
      enabled: yes
  - name: install wget
    yum:
      name: wget
      state: latest
  # - name: remove the Apache package
  #   yum:
  #     name: httpd
  #     state: absent
  - name: Install a list of packages
    yum:
      name:
        - nginx
        - postgresql
        - postgresql-server
      state: present